### ISSUE TITLE
Your hashtable is worse than my hashtable

### ISSUE THREAD

**Issue by go-li** [cznic/hash#1]
Nazdar. Tvoja hash tabulka je horsia nez moja. 
https://github.com/go-li/demo/blob/master/hashtable1.go
reasons:
My hashtable is faster than yours
My hashtable is faster than go builtin map
My table can be compiled using the generics supporting gccgo I've developed
My hashtable is a double slice map supporting any combination of []keys and []values slice
Experts can also use my table in single slice mode too, that is only []key slice, containing values in their own key struct
Users can write their own hash function, doing this right results in same or better performance than builtin map
It provides a full features including insertion , deletion, fetch, and a vacuum operation
Vacuum operation is faster than creating a new map and moving all elements to it.

**Comment by cznic** [comment]
I can't find any benchmarks in the linked repository. How did you get the values?

**Comment by cznic** [comment]
On a second look at the linked code, I noticed it's actually not valid Go code. Contributions are welcome, but I'm going to close the issue for now.
